import Head from 'next/head'
import Image from 'next/image'

import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { Hero } from '@/components/Hero' 
import { Gallery } from '@/components/Gallery' 
import { Services } from '@/components/Services'
import { Contact } from '@/components/Contact'



export default function Home() {
  return (
    <>
      <Head>
        <title>Electrometales</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Header/>
      <main className="min-h-[60vh]">
        <Hero/> 
        <Services/>
        <Gallery/>
        <Contact/>
      </main>
      <Footer/>
    </>
  )
}
